# Generated by Django 2.1 on 2018-09-01 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('started_at', models.DateField(verbose_name='Data de início')),
                ('finished_at', models.DateField(verbose_name='Data de fim')),
                ('objective', models.CharField(max_length=250, verbose_name='Objetivo')),
                ('specification', models.TextField(verbose_name='Espeficificação')),
                ('attachment', models.FileField(upload_to='attachments', verbose_name='Anexo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Usuários')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'Projetos',
                'verbose_name': 'Projeto',
            },
        ),
    ]
