# Generated by Django 2.1 on 2018-09-22 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('EE', 'Em execução'), ('PA', 'Parado'), ('AR', 'Aguardando recurso'), ('CD', 'Concluído')], default='EE', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
